<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!-- This will be the file we use to describe the 3-wheeled car in-class -->
    <xacro:include filename="general_include.xacro"/>

    <xacro:property name="chasis_x" value="0.175"/>
    <xacro:property name="chasis_y" value="0.105"/>
    <xacro:property name="chasis_z" value="0.055"/>

    <xacro:property name="wheel_diameter" value="0.035"/>
    <xacro:property name="wheel_width" value="0.03"/>
    <xacro:property name="front_wheel_diameter" value="0.0175"/>


    <!-- Base Link -->
    <link name="base_link">
    </link>

    <!-- Base to Chasis joint -->
    <joint name="chasis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chasis_link"/>
        <origin xyz ="-0.07 0 0"/>
    </joint>

    <!-- Chasis of the robot -->
    <link name="chasis_link">
        <visual>
            <origin xyz="${chasis_x/2} 0 ${chasis_z/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chasis_x} ${chasis_y} ${chasis_z}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="${chasis_x/2} 0 ${chasis_z/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chasis_x} ${chasis_y} ${chasis_z}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="1" x="${chasis_x}" y="${chasis_y}" z="${chasis_z}">
                <origin xyz="${chasis_x/2} 0 ${chasis_z/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Joint for Right wheel -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="chasis_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0.07 ${-(chasis_y/2 + wheel_width/2)} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <!-- Right wheel link -->
    <link name="right_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_diameter}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_diameter}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.08" length="${wheel_width}" radius="${wheel_diameter}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Joint for Left wheel -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="chasis_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0.07 ${(chasis_y/2 + wheel_width/2)} 0" rpy="${-(pi/2)} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Left wheel link -->
    <link name="left_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_diameter}"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_diameter}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.08" length="${wheel_width}" radius="${wheel_diameter}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Joint for Front Wheel-->
    <joint name="wheel_front_joint" type="fixed">
        <origin xyz="0.16 0 ${-front_wheel_diameter}"/>
        <parent link="chasis_link"/>
        <child link="wheel_front_link"/>
    </joint>

    <!-- Link for Front wheel -->
    <link name="wheel_front_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${front_wheel_diameter}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${front_wheel_diameter}"/>
            </geometry>
        </collision>

        <xacro:inertial_sphere mass="0.01" radius="${front_wheel_diameter}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <xacro:include filename="example_gazebo.xacro" />
</robot>