controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  publish_rate: 50.0
  
  base_frame_id: chasis_link
  left_wheel_names: ['left_wheel_joint']
  right_wheel)names: ['right_wheel_joint']
  wheel_separation: 0.14
  wheel_radius: 0.0175

  use_stamed_vel: false
